Nc news 07
crissu91/fe-news-app pull request #5
Opened 2023-07-18 13:41 UTC by crissu91

2023-07-19 09:09 UTC, Beth-McCormack requested changes
This is looking good so far! 
Please could you add some visual feedback for the user for if the patch request fails, as currently the screen goes white. 
I also dont think the error handling you have is working how you expect - currently its `Cannot read properties of undefined (reading 'status')`
Please have a go at implementing this and submit another PR 🙂

2023-07-19 09:59 UTC, NRMSMITH requested changes
Hey! Functionally, this is working, but it's a bit jarring for the user - I think you need to readdress how you display the error to the user. Have a look at my comment inside :)

Once you've done this, please resubmit. 😄 🚀

2023-07-19 09:59 UTC, NRMSMITH commented on src/components/SingleArticle.jsx
> +        return (
You've made the effort to decrement the votes, but you're actually returning a different component and therefore not showing the decrement.

How about conditionally rendering a p tag that suggests they should try again?

2023-07-19 11:18 UTC, xViolaine approved these changes

2023-07-19 11:18 UTC, xViolaine commented on src/components/SingleArticle.jsx
> +
Your voting system currently allows user to Upvote an Article multiple times. The button isn't disabled between votes, allowing users to inflate votes by spam-clicking the button - this is not false per se, but just something for you to consider :)

2023-07-19 11:18 UTC, xViolaine commented on src/components/SingleArticle.jsx
> +
The error works fine!

2023-07-19 11:20 UTC, merged

2023-07-20 07:43 UTC, RichardNeat reviewed
Nice one Cristina - just one comment below to take a look at but otherwise you're good to merge :)

2023-07-20 07:43 UTC, RichardNeat commented on src/components/Error.jsx
> +        <div className="error">
Could we use anything better than a div here?