Nc news 09
crissu91/fe-news-app pull request #7
Opened 2023-07-20 09:16 UTC by crissu91

2023-07-20 10:09 UTC, NRMSMITH requested changes
Have a think about what your useEffect is dependent on :)

2023-07-20 10:09 UTC, NRMSMITH commented on src/components/AllTopics.jsx
> +    },[])
What is this useEffect dependent on?

2023-07-20 14:51 UTC, mezzDavies requested changes
Currently when the user clicks on a topic the url changes to this - `/articles?topic=coding` ideally we want it to be `/topics/coding `- this makes much more sense to the user as we are moving forwards from the `topics` page.  Put another way the endpoint we use to access the API doesn't have to be the url that is shown on the front end. Please implement this. 🙂

Having spoken to Niamh I think this is what she was getting at with her comment earlier - you do not need topics in the dependency array 👍

2023-07-21 07:37 UTC, NRMSMITH commented
This looks brill Cristina! 🚀 Apologies about my misleading comment earlier! 😓 That's my bad!! 

Merge away 😄

2023-07-21 07:39 UTC, merged